name: aoc2021
version: 0
license-file: LICENSE

executable:
  main: Main.hs
  source-dirs:
    - src

dependencies:
  - base >= 4.12 && < 4.16
  - finite-typelits
  - ghc-typelits-knownnat
  - ghc-typelits-natnormalise
  - indexed-list-literals
  - vector-sized

ghc-options:
  - -Wall
  - -fplugin GHC.TypeLits.KnownNat.Solver
  - -fplugin GHC.TypeLits.Normalise
  - -fdefer-typed-holes
  - -Wincomplete-patterns
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - LambdaCase
  - InstanceSigs
  - ImportQualifiedPost
  - MultiParamTypeClasses
  - OverloadedStrings
  - PatternSynonyms
  - QuantifiedConstraints
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns
